[programs.localnet]
anchor_escrow = "6nLdArXkxYFfuuFy7Ph7LQKJTBjX1vRcsyRAAKY6Hfao"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.27.0" # `anchor-cli` version to use
solana_version = "1.17.0" # Solana version to use
